default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  username: <%= ENV['LOCAL_DATABASE_USERNAME'] %>
  password: <%= ENV['LOCAL_DATABASE_PASSWORD'] %>

development:
  <<: *default
  <<: *local
  database: croqui_api_development

test:
  <<: *default
  <<: *local
  database: croqui_api_test

production:
  <<: *default
  url: <%= ENV['PRODUCTION_DATABASE_URL'] %>
